"""initial schema

Revision ID: 3d5e4a889d3a
Revises: 
Create Date: 2026-07-02 16:02:14.560015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5e4a889d3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('patente', sa.String(length=20), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('kilometraje_actual', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_vehicles_patente'), 'vehicles', ['patente'], unique=True)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('tipo_otro_texto', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('taller_nombre', sa.String(length=100), nullable=True),
    sa.Column('taller_contacto', sa.String(length=100), nullable=True),
    sa.Column('proximo_fecha_estimada', sa.Date(), nullable=True),
    sa.Column('proximo_km_estimado', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_vehicle_id'), 'maintenance_tasks', ['vehicle_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_task_id', sa.Integer(), nullable=False),
    sa.Column('filename_original', sa.String(length=255), nullable=False),
    sa.Column('filename_stored', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename_stored')
    )
    op.create_index(op.f('ix_attachments_maintenance_task_id'), 'attachments', ['maintenance_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_maintenance_task_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_maintenance_tasks_vehicle_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_vehicles_patente'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
