"""add task types table

Revision ID: 6e5490901a2c
Revises: 6436173e100f
Create Date: 2026-07-06 21:15:41.192788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5490901a2c'
down_revision: Union[str, Sequence[str], None] = '6436173e100f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('permite_recordatorio', sa.Boolean(), nullable=False),
    sa.Column('es_protegido', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_types_slug'), 'task_types', ['slug'], unique=True)
    # ### end Alembic commands ###

    task_types_table = sa.table(
        'task_types',
        sa.column('slug', sa.String),
        sa.column('label', sa.String),
        sa.column('permite_recordatorio', sa.Boolean),
        sa.column('es_protegido', sa.Boolean),
    )
    seed = [
        ('cambio_aceite', 'Cambio de aceite'),
        ('filtro_aceite', 'Filtro de aceite'),
        ('filtro_aire', 'Filtro de aire'),
        ('filtro_combustible', 'Filtro de combustible'),
        ('frenos', 'Frenos / pastillas'),
        ('neumaticos', 'Neumáticos / alineación'),
        ('bateria', 'Batería'),
        ('correa_distribucion', 'Correa de distribución'),
        ('refrigerante', 'Refrigerante'),
        ('revision_general', 'Revisión general / service'),
        ('itv_vtv', 'ITV / VTV (revisión técnica)'),
    ]
    op.bulk_insert(
        task_types_table,
        [
            {'slug': slug, 'label': label, 'permite_recordatorio': True, 'es_protegido': False}
            for slug, label in seed
        ]
        + [{'slug': 'otro', 'label': 'Otro', 'permite_recordatorio': False, 'es_protegido': True}],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_types_slug'), table_name='task_types')
    op.drop_table('task_types')
    # ### end Alembic commands ###
