"""add intervalo_km e intervalo_meses a task_types

Revision ID: d36107970598
Revises: 6e5490901a2c
Create Date: 2026-07-07 08:37:16.232515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36107970598'
down_revision: Union[str, Sequence[str], None] = '6e5490901a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_types', sa.Column('intervalo_km', sa.Integer(), nullable=True))
    op.add_column('task_types', sa.Column('intervalo_meses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_types', 'intervalo_meses')
    op.drop_column('task_types', 'intervalo_km')
    # ### end Alembic commands ###
