"""add carga_anterior_registrada to fuel_logs

Revision ID: ff9cd7ece752
Revises: b19218d3ba5a
Create Date: 2026-07-03 09:13:15.544559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9cd7ece752'
down_revision: Union[str, Sequence[str], None] = 'b19218d3ba5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'fuel_logs',
        sa.Column('carga_anterior_registrada', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_logs', 'carga_anterior_registrada')
    # ### end Alembic commands ###
